### ISSUE TITLE
 Missing Encryption Key

### ISSUE THREAD

**Issue by mohammadr3z** [froger-me/wp-remote-users-sync#1]
Hi
This error occurs when I enable the plugin

WP Remote Users Sync is not ready. Edit configuration

Missing Encryption Key
Missing Authentication Key

**Comment by froger-me** [comment]
Hi @mohammadr3z  Yes - it means you have to input encryption and authentication keys of your choosing in the settings of the application.
This is anything you want as long as it's strong like a password, kept secret, and the same across all the website you connect.
