### ISSUE TITLE
Add Support for Woocommerce Subscription when Active/Inactive status change.

### ISSUE THREAD

**Issue by JLAcostaEC** [froger-me/wp-remote-users-sync#10]
When changing the status of the user's subscription (**Active Subscription** - **Inactive Subscription**) the update request for the other site is not generated. (Swicht from **Active** to **Inactive** or vice versa)

All this process is done **automatically** by woocommerce Subscription. The update is only generated when updating a user manually.

Thanks for the help!

:D

**Comment by froger-me** [comment]
Hello @JLAcostaEC - are you talking about the [WooCommerce Subscriptions](https://www.woocommerce.com/products/woocommerce-subscriptions/) plugin specifically?
