### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by SkyBlue1903** [froger-me/wp-remote-users-sync#11]
Please give me full tutorial about using this plugin, from setting up until applying. thanks

**Comment by scotthopkins** [comment]
you could watch this https://www.youtube.com/watch?v=vZKjj0Mclf4

**Comment by froger-me** [comment]
Thank you @scotthopkins - this is what I would have recommended as well. Please make sure to read the pinned comment for minor corrections and more precisions.
