### ISSUE TITLE
Fatal Error when Activating Plugin

### ISSUE THREAD

**Issue by mirrid** [froger-me/wp-remote-users-sync#15]
Plugin could not be activated because it triggered a fatal error.
Failed to create the necessary database table(s).

**Comment by froger-me** [comment]
Hi @mirrid ,
Without more details, it will be impossible to troubleshoot. Please answer the same (unanswered) questions as asked in [this thread](https://wordpress.org/support/topic/plugin-could-not-be-activated-because-it-triggered-a-fatal-error-606/).

**Comment by mirrid** [comment]
Ok well just about every other plugin installs without a problem so maybe its best not to use this.

**Comment by froger-me** [comment]
This is very much up to you. This is a free plugin. You may choose to give back to the community by helping with troubleshooting (or contribute financially to have the dev do it for you), or you may choose not to use it. In any case, that type of comment doesn't help.

Closing the issue.
