### ISSUE TITLE
User created content not transfer to remote site

### ISSUE THREAD

**Issue by vishanjad3175** [froger-me/wp-remote-users-sync#17]
Alex, thank you for such a great plugin. On my first try i was hoping it would transfer user created content to other remote sites (site 1,2,3 production to staging and visa versa for post, images etc,) or generally sync full sites as they are updated live. Sort of replicating sites to an edge server, If and only if the admin choose to apply a full site for user created content or other aspect of site for transfer.

Is this what this plugin is meant for or is only limited to user login credentials, meta data etc. or am i doing something wrong? Please advise.

**Comment by froger-me** [comment]
Hi @vishanjad3175 ,

WPRUS is used to sync users and users data, not posts. It only syncs users across websites.

**Comment by vishanjad3175** [comment]
Thank you. Is this something you would consider as a premium feature for future release?

**Comment by froger-me** [comment]
Hi @vishanjad3175 ,

Although it is possible to implement what you are looking for using the documentation of the plugin and using its communication method theoretically, scaling could be an issue.

There is no plan to go beyond synchronizing user data within the plugin's core and integrations. A plugin developed by a third party developer is a possibility, but I do not have plan to propose a premium version of the plugin myself (no bandwidth for long term maintenance).
