### ISSUE TITLE
2 Bugs Identified

### ISSUE THREAD

**Issue by trademark2k6** [froger-me/wp-remote-users-sync#20]
**Bug 1 - Password Reset not Syncing**

Steps to Reproduce:
1) When you click the "forgot password" option on website A, you are sent a email with a link to reset password.
2) User clicks link and resets password which they can immediately use on Website A.
3) This new password is not Synced across to Website B, therefore user can not login on Website B.

System:
WC v3.5.0
WP Remote Sync v1.2.6
Wordpress v4.9.8

**Bug 2 - Woocommerce Meta Not Copying Across**

Steps to Reproduce:
1) Visit website 1, add items to basket, register during checkout (name, delivery address, phone number, etc), and see the order summary page
2) Visit website 2, and login, login is successful.
3) Go to my account -> account details
4) The name, address, postcode, phone is not been copied over. 

System:
WC v3.5.0
WP Remote Sync v1.2.6
Wordpress v4.9.8

**Comment by froger-me** [comment]
Answered [here](https://wordpress.org/support/topic/2-bugs-identified/) - closing.
