### ISSUE TITLE
Not login

### ISSUE THREAD

**Issue by xrasolx** [froger-me/wp-remote-users-sync#21]
Hello,

I have installed this plugin and set it up based on the tutorials on this video:
[WP Remote Users Sync Setup](https://www.youtube.com/watch?v=vZKjj0Mclf4&t=164s)

I have done everything exactly as it was shown in the video, but when I login to website number 1, I’m not getting logged into website number 2 (so when I visit website number 2 I am not logged in).

I have checked my permalink in WordPress > setting > General and they are exaclly as how I put them in WP Remote Users Sync settings on both websites.

I also checked the data base of both of my website and went into wp-options > home . the url was exact match.

I have tried to check and uncheck “Force Login Redirects & Logout Everywhere” & “Force Disable Login Redirects & Logout Everywhere” in both of my website but that did not help either.

There must be something wrong somewhere which I cannot figure out.

I’ll appreciate in advance if anyone here can help me resolve this issue.

Thank you

**Comment by froger-me** [comment]
Hi @xrasolx ,

As asked [here](https://wordpress.org/support/topic/login-and-log-out-are-not-working/), does the issue occur with 2 fresh installs of WordPress, WPRUS and default themes only?

**Comment by froger-me** [comment]
No answer - closing
