### ISSUE TITLE
Multisite usage

### ISSUE THREAD

**Issue by dj-jetta** [froger-me/wp-remote-users-sync#24]
Hi Alexandre,

i work for a company and we have more than 100 WordPress websites with different content distributet over a few multisites. My idea has been to set up a base single site as a userhub and connect all the other sites to this site. But there is a problem with connecting the sites in the Multisites. With the base installation in each multisite there is no problem and it connects in both directions. But with all pages with a ID higher than 1 it is only possible to connect in one direction. For example it work to connect from a site with the ID2 in a Multisite in direction to the user hub, but the connection from userhub page to the same Multisite site don't not work. Here is a part of the activity log attached. 

[issue_activity_log.txt](https://github.com/froger-me/wp-remote-users-sync/files/5587843/issue_activity_log.txt)

Please can you help.

Kind regards
Daniel

**Comment by renegademarketer** [comment]
@dj-jetta did you find a fix for this?

**Comment by dj-jetta** [comment]
@renegademarketer no, i hoped the developer will help, but he didn’t answer to my request.

 

Von: renegademarketer <notifications@github.com> 
Gesendet: Donnerstag, 25. Februar 2021 02:55
An: froger-me/wp-remote-users-sync <wp-remote-users-sync@noreply.github.com>
Cc: dj-jetta <support@more-creative-arts.de>; Mention <mention@noreply.github.com>
Betreff: Re: [froger-me/wp-remote-users-sync] Multisite usage (#24)

 

@dj-jetta <https://github.com/dj-jetta>  did you find a fix for this?

**Comment by froger-me** [comment]
Hi @dj-jetta and @renegademarketer !
Sorry for addressing that so late. Unfortunately currently WPRUS does not support multisite - it's very much more difficult to build a test env, test, and debug with multisite.
WPRUS was originally intended for webmasters who wish to sync data between sites *without* using multisite, but still get the benefits of a common user base with extra granularity and a distributed ecosystem.
However, pull requests are always welcome ;).
I'm gonna go ahead and close the issue.
