### ISSUE TITLE
User role not carried over

### ISSUE THREAD

**Issue by linamani** [froger-me/wp-remote-users-sync#26]
I have wp-remote-users-sync installed on 2 sites.  I create a new user on site A with role set to 'administrator', account creation gets carried over to site B fine except for the role.  On site B the new user is set to 'subscriber', not 'administrator' like it is on site A.  
Site A has everything checked for outgoing actions and site B has everything checked for incoming actions so in theory it should work.  And everything does get set fine except for the role.

**Comment by froger-me** [comment]
Hi @linamani !

It is usually good practice to add a comment with the reason was an issues was closed, in case another user stumbles upon the topic for similar issues.

Could you please elaborate succinctly?

**Comment by linamani** [comment]
Sorry, it was completely my fault.. I didn't read that I have to specify
which user roles to transfer on outgoing actions (leave empty to transfer
none).  On incoming it says leave empty to transfer all.
I can go back and add a comment.
