### ISSUE TITLE
Seperate Password emails for each site?

### ISSUE THREAD

**Issue by iMansoorAliKhan** [froger-me/wp-remote-users-sync#27]
We have installed ad configrued your plugin on 2 sites and the passwords are not shared . When I signup on site 1 I get 2 emails with seperate password for each of the sites.

- I will have 12 sites linked togather, and having each site a different password is not helping using this plugin.
- We selected this plugin so that all of those synced sites can have 1 login works for all
- I also have selected some meta fields but they are also not synced across domains.

**Comment by froger-me** [comment]
Out of scope - closing
