### ISSUE TITLE
Does your solution support this use case?

### ISSUE THREAD

**Issue by gujingc** [froger-me/wp-remote-users-sync#29]
We are looking for a use case like this.

We have an existing multisite system which we would like to keep as is.

We are looking at building a new multisite system (Multisite B) which runs in parallel to the current multisite system. (Multisite A)

When a user signs up on the site 1 of the Multisite A, he/she will be automatically provided access to a corresponding subsite in Multisite B.

Do you support a use case like this?

**Comment by froger-me** [comment]
Hello @gujingc !
Although I haven't tested with multisite (and do not actively support multisite), I have had feedback that some thing do not work in some particular cases. This has to do with how cookies are set I believe, and multisite has 3 different ways to be set up (subfolder, subdomain, and multiple domains).  

Without having tested, from the top of my head, I would say your use case may not work in the latter case (multiple domains - unless the user gets connected to the corresponding subsite in Multisite B directly), may work in the case of subdomains (provided it's possible to handle the network login on your end when a user is connected to a subsite, or if the user gets connected to the corresponding subsite in Multisite B directly) and is likely to work in the case of subfolders.  

All these specualtions are taking for granted that the user has been added to the corresponding subsite in Multisite B and has access to it (basicaly, [add_user_to_blog](https://codex.wordpress.org/WPMU_Functions/add_user_to_blog) has been called at some point).

**Comment by gujingc** [comment]
Alexander,

Thank you for the reply. 

There are 2 scenarios.

Scenario 1, we set up a single WP site, and export all the network users in the multisite into this new single WP.

Scenario 2, we set up a multisite whose subsite structure mirrors the existing subsite, 

Just to confirm, do you consider Scenario 1 possible but Scenario 2 might be more challenging? or otherwise? Or not work at all?

**Comment by froger-me** [comment]
Hi!
I honestly cannot vouch for any of the scenarios, because I'd have to test them and it's not supported.

What is the most important is what happens on the receiving site - so if the receiving site is a subsite part of a multisite network, this is where the unknown behavior comes into play. Multisite to classic WP should be fine, but that's theoretical - testing is always the best option ;)
