### ISSUE TITLE
Not compatible with theseoframework

### ISSUE THREAD

**Issue by extremeshok** [froger-me/wp-remote-users-sync#3]
Results in a fatal error, when navigating to the settings page "/wp-admin/admin.php?page=wprus"

https://wordpress.org/plugins/autodescription/

https://theseoframework.com

**Comment by froger-me** [comment]
Hi @extremeshok 
The plugin has been updated quite a lot - could you confirm the issue is still there? If yes, could you please indicate the exact message from PHP logs?

**Comment by froger-me** [comment]
More than a week without activity - closing.
