### ISSUE TITLE
Users that are not suppose to syncing are syncing

### ISSUE THREAD

**Issue by ayearsley1** [froger-me/wp-remote-users-sync#32]
I have just set up the user sync and the users that have the roles should be set up to sync are not syncing but users with roles not listed are syncing. 

![primarysite](https://user-images.githubusercontent.com/82669481/115053069-f1df6100-9e9b-11eb-8147-9c104151ca5d.png)
![remote site](https://user-images.githubusercontent.com/82669481/115053072-f441bb00-9e9b-11eb-8c7f-deb7f36821de.png)

**Comment by quinten1333** [comment]
Hi,

I came across this too and dove in the code. The `notify_remote` function in the create api is reponsible for creating new users ont he remote.

As you can see in [the source code](https://github.com/froger-me/wp-remote-users-sync/blob/6ccc0c9f8e35aba202ed067ff9448fd7ae26b607/inc/api/class-wprus-api-create.php#L98), there is no role checking of any kind here. The title and placement suggests that it dictates all sync actions but that box is only used by the role api in[ this line](https://github.com/froger-me/wp-remote-users-sync/blob/6ccc0c9f8e35aba202ed067ff9448fd7ae26b607/inc/api/class-wprus-api-role.php#L112).

Hope this helps!

**Comment by froger-me** [comment]
Hello!

  
The roles settings is here to indicate whether the indicated **role** should be synced when the user is synced - but all the users are synced with this plugin, unless it is altered with hooks and filters.
