### ISSUE TITLE
Profile image does not synchronize

### ISSUE THREAD

**Issue by yovamacua** [froger-me/wp-remote-users-sync#66]
Hello the plugin is excellent but I have the problem that the profile images of users are not synchronized, I'm using the plugin one avatar, I would like the image is also updated on the second site to update it in the first I'm trying with the meta data but it does not work, could you help me?

**Comment by seu-steve** [comment]
Can't speak to One Avatar, but we're using Basic User Avatars which syncs fine across our sites.

**Comment by froger-me** [comment]
Profile pictures aside from Gravatar are a third-party feature (out of scope).
