### ISSUE TITLE
Hope Everything is Well?

### ISSUE THREAD

**Issue by jesusboy001** [froger-me/wp-remote-users-sync#71]
Hi. I just want to confirm that you're still alive and well. It's a little unusual to see a developer develop such an amazing plugin and leave it abandoned. The plugin is so great that it can actually be a paid plugin if that would be what it takes to see it constantly updated. Anyways, I hope you're doing well wherever you are. Thanks for this gift to the WordPress community.

**Comment by froger-me** [comment]
Concern is very much appreciated - sometimes life catches up and time is scarce, but it's a good thing long term compatibility is at the core of this plugin!
