### ISSUE TITLE
Multisite / general user sync not working

### ISSUE THREAD

**Issue by chrisjpoole** [froger-me/wp-remote-users-sync#75]
I have the plugin installed on two sites, one is a multisite (site A) and one is not (site B). When I create the user on site A it is also created on site B. But when I delete the user on site A it is not deleted on site B. When I click the test button it says successful so I presuming the action is not being fired? 

As a side note one time I created a user on site A and it created it 3 times on site B. All with the same username but different user ID's

**Comment by froger-me** [comment]
fixed in 2.0 ; as for the side notes, ID divergence is normal, IDs are not used for sync ; see FAQ
