### ISSUE TITLE
2.0 is broken

### ISSUE THREAD

**Issue by intlCEA** [froger-me/wp-remote-users-sync#76]
Synchronise WordPress Users across Multiple Sites.

Version 2.0 | By [Alexandre Froger](https://froger.me/) | [View details](https://iceastem.org/wp-admin/plugin-install.php?tab=plugin-information&plugin=wp-remote-users-sync&TB_iframe=true&width=600&height=550)
 This plugin failed to load properly and is paused during recovery mode.

An error of type E_PARSE was caused in line 117 of the file /homepages/23/d127293178/htdocs/ICEAStem/wp-content/plugins/wp-remote-users-sync/inc/class-wprus-logger.php. Error message: syntax error, unexpected ')'

**Comment by intlCEA** [comment]
WordPress version 6.4.1
Active theme: Twenty Twenty-Four (version 1.0)
Current plugin: WP Remote Users Sync (version 2.0)
PHP version 7.2.34

**Comment by froger-me** [comment]
Hi @intlCEA 
Thank you for the bug report ; it has now been addressed in v2.0.1
