### ISSUE TITLE
Issue: PHP Notice - wprus_user_pending_async_actionscookie cannot be set

### ISSUE THREAD

**Issue by bdktsh** [froger-me/wp-remote-users-sync#92]
### Description

I'm experiencing a PHP Notice when using the WP Remote Users Sync (WPRUS) plugin in a two-website setup. The error message indicates that a cookie (wprus_user_pending_async_actionscookie) cannot be set because headers have already been sent. This issue appears to occur in the class-wprus-api-abstract.php file on line 1097.

### Error Message

`PHP Notice: wprus_user_pending_async_actionscookie cannot be set - headers already sent by on line 0 /wp-content/plugins/wp-remote-users-sync/inc/api/class-wprus-api-abstract.php on line 1097`

### Steps to Reproduce

1. Set up a two-website environment using the WP Remote Users Sync plugin.
2. Attempt to perform an action that triggers wprus_user_pending_async_actionscookie.
3. Observe the PHP Notice in the logs.

### Expected Behavior

Cookies should be set without triggering a "headers already sent" notice.

### Actual Behavior

A PHP Notice is raised because the plugin attempts to set a cookie after headers have already been sent, which may be due to unexpected output or whitespace before setcookie() is called.

### Potential Cause

The issue appears to be related to setcookie() being called after headers are sent, which suggests there may be output sent to the browser before this action. Ensuring that cookies are set before any output should resolve this issue.

### Environment

```
WordPress Version: 6.6.2
PHP Version: 8.0
WPRUS Version: 2.0.4
```

### Additional Context

This setup involves two websites. Any guidance on resolving this issue or adjustments to the plugin code to ensure cookies are set before output would be greatly appreciated.

**Comment by froger-me** [comment]
I was not able to reproduce with default/supprted themes and supported plugins.

**Comment by bdktsh** [comment]
Right, it is actually connected to the Awesome Support plugin.
